#pragma once
#define INCORRECT_WRITE_PACKET_SIZE 1
#define INCORRECT_READ_PACKET_SIZE 2
#define INCORRECT_RX_HEADER 3
#define CHECKSUM_ERROR 4
#define HOST_RX_BUFFER_SMALL 5
#define UNEXPECTED_ID 6
#define SERVO_ERROR 7
#define PACKET_TIMEOUT 8
#define PACKET_SEND_FAILED 9
#define CONNECTION_LOST 10
#define INVALID_ARGUMENT 11
#define ID_IN_USE 12
#define LEN_MISMATCH 13
#define RANGE_ERROR 14